### ISSUE TITLE
Error while trying to save a session

### ISSUE THREAD

**Issue by Thanos-DB** [JoseCM/PDFSessions#3]
Hi,

new around. Your project seems really interesting, and nice of you to share.
I copied the  Javascript as you said and i see the menu.
The thing is that when i try to save a session i get "An internal error occurred" and nothing gets saved.
Any solution?

-Thanos

**Comment by Thanos-DB** [comment]
Ok found the problem.
So if you have the same problem then do as follows:
Edit>Preferences>Javascript

Then check:
enable menu items JavaScript execution privileges

**Comment by prateekdaniels** [comment]
An Awesome Script mate. Three cheers !!!!!!!
